language: minimal

services: docker

env: Dimg=scivision/opencoarrays_fortran; Dname=fortran-ubuntu

before_install:
- docker run -d --name $Dname -v $TRAVIS_BUILD_DIR:/travis -w /travis $Dimg tail -f /dev/null

# prepend $Dcmd to run commands inside the Docker container
- export Dcmd="docker exec -t $Dname bash -c"

install:
# for this example, I already installed everything I need in the image previously created by the Dockerfile

script:
# all commands must be quoted
- $Dcmd "ctest --build-and-test . build --build-generator 'Unix Makefiles' --test-command ctest"
